// <auto-generated />
namespace Jude.ES365.ShopApp.DatAcc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Fuiy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fuiy));
        
        string IMigrationMetadata.Id
        {
            get { return "201806221759557_Fuiy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
